# Generated by Django 3.2.8 on 2021-10-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=100)),
                ('own_website', models.CharField(max_length=100)),
                ('myPhone_number', models.CharField(max_length=50)),
                ('now_city', models.CharField(max_length=100)),
                ('my_age', models.CharField(max_length=20)),
                ('my_level', models.CharField(max_length=100)),
                ('my_email', models.CharField(max_length=100)),
                ('freelance_status', models.CharField(max_length=50)),
                ('about_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FactsInfoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.CharField(max_length=30)),
                ('projects', models.CharField(max_length=30)),
                ('support_hours', models.CharField(max_length=30)),
                ('hard_workers', models.CharField(max_length=30)),
                ('facts_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyInfoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/')),
                ('myName', models.CharField(max_length=50)),
                ('mySurname', models.CharField(max_length=50)),
                ('my_location_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Web', 'Web Site'), ('TgBot', 'Telegram Bot')], max_length=100)),
                ('client', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='articles/')),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('project_url', models.CharField(max_length=100)),
                ('about_project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsInfoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_status', models.CharField(max_length=10)),
                ('css_status', models.CharField(max_length=10)),
                ('js_status', models.CharField(max_length=10)),
                ('python_status', models.CharField(max_length=10)),
                ('django_status', models.CharField(max_length=10)),
                ('react_status', models.CharField(max_length=10)),
                ('skill_text', models.TextField()),
            ],
        ),
    ]
