# Generated by Django 3.2.8 on 2021-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category_inner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
