# Generated by Django 3.2.8 on 2021-10-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_category_inner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category_inner',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category_2',
            field=models.CharField(choices=[('Web', 'Web'), ('TgBot', 'TgBot')], max_length=100, null=True),
        ),
    ]
