# Generated by Django 3.2.8 on 2021-10-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20211024_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_1',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_2',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_3',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
    ]
